blank_issues_enabled: false
contact_links:
  - name: 🧑‍💻 Dartotsu Help on Discord
    url: https://discord.gg/eTa2GKtE
    about: Get support, ask questions, and join the community discussions.

  - name: 📱 Dartotsu Help on Telegram
    url: https://t.me/Dantotsu_alpha
    about: Connect with the community, ask questions, and get help directly on Telegram.
