name: CI
on:
  push:
    branches: main
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build apk --split-per-abi

      - name: Upload APK to Discord
        run: |
          curl -F "payload_json={\"content\": \"Android x86_64 ${{ github.sha}}\"}" \
             -F "file=@build/app/outputs/flutter-apk/app-x86_64-release.apk" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
        
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build windows
      - name: Archive App
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Dantotsu-${{github.sha}}-windows.zip
          directory: build\windows\x64\runner\Release
      - name: Upload Windows ZIP to Discord
        shell: pwsh
        run: ./scripts/upload-to-discord.ps1 -webhookUrl ${{ secrets.DISCORD_WEBHOOK_URL }} -filePath build\windows\x64\runner\Release\Dantotsu-${{github.sha}}-windows.zip
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux
      - name: Archive app
        uses: thedoctor0/zip-release@master
        with:
            type: 'zip'
            filename: Dantotsu-${{github.sha}}-linux.zip
            directory: build/linux/x64/release/bundle
      - name: Upload Linux ZIP to Discord
        run: |
            curl -F "payload_json={\"content\": \"Linux ${{ github.sha}}\"}" \
               -F "file=@build/linux/x64/release/bundle/Dantotsu-${{github.sha}}-linux.zip" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
  build_ios_and_macos:
    runs-on: macos-latest
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: flutter build macos
      - name: Archive App
        uses: thedoctor0/zip-release@master
        with:
            type: 'zip'
            filename: Dantotsu-${{github.sha}}-macos.zip
            directory: build/macos/Build/Products/Release
      - name: Upload MacOs ZIP to Discord
        run: |
            curl -F "payload_json={\"content\": \"Macos ${{ github.sha}}\"}" \
               -F "file=@build/macos/Build/Products/Release/Dantotsu-${{github.sha}}-macos.zip" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
