name: CI
on:
  push:
    branches: main
jobs:
  # build_android:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cloing repository
  #       uses: actions/checkout@v4
  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: 3.24.1
  #     - run: flutter pub get
  #     - run: flutter build apk --split-per-abi

  #     - name: Upload APK to Discord
  #       run: |
  #         curl -F "payload_json={\"content\": \"Android x86_64 ${{ github.sha}}\"}" \
  #            -F "file=@build/app/outputs/flutter-apk/app-x86_64-release.apk" \
  #            ${{ secrets.DISCORD_WEBHOOK_URL }}
        
  # build_windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Cloing repository
  #       uses: actions/checkout@v4
  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: 3.24.1
  #     - run: flutter pub get
  #     - run: flutter build windows
  #     - name: Archive App
  #       uses: thedoctor0/zip-release@master
  #       with:
  #         type: 'zip'
  #         filename: Dantotsu-${{github.sha}}-windows.zip
  #         directory: build\windows\x64\runner\Release
  #     - name: Upload Windows ZIP to Discord
  #       shell: pwsh
  #       run: ./scripts/upload-to-discord.ps1 -webhookUrl ${{ secrets.DISCORD_WEBHOOK_URL }} -filePath build\windows\x64\runner\Release\Dantotsu-${{github.sha}}-windows.zip
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Download last SHA artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: dart.yml
          name: last-sha
          path: .
        continue-on-error: true
      - name: Get Commits Since Last Run
        run: |
          if [ -f last_sha.txt ]; then
            LAST_SHA=$(cat last_sha.txt)
          else
            # Fallback to first commit if no previous SHA available
            LAST_SHA=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "Commits since $LAST_SHA:"
          # Accumulate commit logs in a shell variable
          COMMIT_LOGS=$(git log $LAST_SHA..HEAD --pretty=format:"● %s ~%an [֍](https://github.com/${{ github.repository }}/commit/%H)")
          # URL-encode the newline characters for GitHub Actions
          COMMIT_LOGS="${COMMIT_LOGS//'%'/'%25'}"
          COMMIT_LOGS="${COMMIT_LOGS//$'\n'/'%0A'}"
          COMMIT_LOGS="${COMMIT_LOGS//$'\r'/'%0D'}"
          # Append the encoded commit logs to the COMMIT_LOG environment variable
          echo "COMMIT_LOG=${COMMIT_LOGS}" >> $GITHUB_ENV
          # Debugging: Print the variable to check its content
          echo "$COMMIT_LOGS"
          echo "$COMMIT_LOGS" > commit_log.txt
          # Extract branch name from github.ref
          BRANCH=${{ github.ref }}
          BRANCH=${BRANCH#refs/heads/}
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
        shell: /usr/bin/bash -e {0}
        env:
          CI: true
        continue-on-error: true
      - name: Save Current SHA for Next Run
        run: echo ${{ github.sha }} > last_sha.txt
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux
      - name: Archive app
        uses: thedoctor0/zip-release@master
        with:
            type: 'zip'
            filename: Dantotsu-${{github.sha}}-linux.zip
            directory: build/linux/x64/release/bundle
      - name: Upload Linux ZIP to Discord
        run: |
            curl -F "payload_json={\"content\": \"Linux ${{ github.sha}}\"}" \
               -F "file=@build/linux/x64/release/bundle/Dantotsu-${{github.sha}}-linux.zip" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
  # build_ios_and_macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Cloing repository
  #       uses: actions/checkout@v4
  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: 3.24.1
  #     - run: flutter pub get
  #     - run: flutter build ios --release --no-codesign
  #     - run: flutter build macos
  #     - name: Archive App
  #       uses: thedoctor0/zip-release@master
  #       with:
  #           type: 'zip'
  #           filename: Dantotsu-${{github.sha}}-macos.zip
  #           directory: build/macos/Build/Products/Release
  #     - name: Upload MacOs ZIP to Discord
  #       run: |
  #           curl -F "payload_json={\"content\": \"Macos ${{ github.sha}}\"}" \
  #              -F "file=@build/macos/Build/Products/Release/Dantotsu-${{github.sha}}-macos.zip" \
  #              ${{ secrets.DISCORD_WEBHOOK_URL }}
