name: Fetch Release Assets

on:
  push:
    branches:
      - test

jobs:
  fetch-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Release Assets
        id: get_assets
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.FINE_GRAIN_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{github.repository}}/releases/assets/ASSET_ID \
          |  > assets.txt

      - name: Show Asset URLs
        run: |
          cat assets.txt