name: RELEASE
on:
  push:
    tags: 
      - "v*.*.*"
jobs:
  build_android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build apk
      - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Dantotsu_Android_${{github.ref}}.apk
      - name: Android Apk Release
        uses: softprops/action-gh-release@master
        with:
            files: build/app/outputs/flutter-apk/Dantotsu_Android_${{github.ref}}.apk
  build_windows:
    runs-on: windows-latest
    permissions: 
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build windows
      - name: Archive App
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Dantotsu_Windows_${{github.ref}}.zip
          directory: build\windows\x64\runner\Release
      - run: ls build\windows\x64\runner\Release
      - name: Release Windows Zip
        uses: softprops/action-gh-release@master
        with:
            files: build/windows/x64/runner/Release/Dantotsu_Windows_${{github.ref}}.zip
        
    
  build_linux:
    runs-on: ubuntu-latest
    permissions: 
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux
      - name: Archive app
        uses: thedoctor0/zip-release@master
        with:
            type: 'zip'
            filename: Dantotsu_Linux_${{github.ref}}.zip
            directory: build/linux/x64/release/bundle
      - name: Release Linux Zip
        uses: softprops/action-gh-release@master
        with:
            files: build/linux/x64/release/bundle/Dantotsu_Linux_${{github.ref}}.zip
  build_ios_and_macos:
    runs-on: macos-latest
    permissions: 
        contents: write
        pull-requests: write
        repository-projects: write
    steps:
      - name: Cloing repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Release ios App
        uses: softprops/action-gh-release@master
        with:
            files: build/ios/iphoneos/Runner.app
      - run: flutter build macos
      - name: Archive App
        uses: thedoctor0/zip-release@master
        with:
            type: 'zip'
            filename: Dantotsu_MacOS_${{github.ref}}.zip
            directory: build/macos/Build/Products/Release
      - name: Release MacOS Zip
        uses: softprops/action-gh-release@master
        with:
            files: build/macos/Build/Products/Release/Dantotsu_MacOS_${{github.ref}}.zip